# Auto-Generated by `apipkgen` package:
# See apipkgen docs for help

#' Access to Sensibo Sky API V2 for Smart A/C Remote Control
#' @importFrom httr VERB stop_for_status content
#' @importFrom jsonlite fromJSON
#' @importFrom glue glue
#' @name sensibo.sky-package
#' @aliases sensibo.sky
#' @docType package
NULL
